### ISSUE TITLE
Question on the compute-efficiency of the implementation

### ISSUE THREAD

**Issue by younggyoseo** [NM512/dreamerv3-torch#20]
Hi, thanks for a nice implementation of DreamerV3! This should be very useful. I have a quick question, how does it compare with DreamerV3 JAX implementation in terms of compute costs? Like, how long does it take to run a single run with this Torch implementation and JAX implementation? It should be very informative and helpful if you might perhaps be able to provide this information!

**Comment by NM512** [comment]
Hi,

Thanks for asking the question.
let me share the comparison on my local device.

In this comparison, I used Model size S of networks introduced in the paper and used DMC vision task.
Following conditions are in my local PC environment.


My PC:
- Intel(R) Core(TM) i9-9900K CPU (8cores, 3.60GHz) 
- RAM: 32 GB DDR4
- GPU: NVIDIA GeForce RTX 3080ti GDDR6X 12GB
- OS: Ubuntu 20.04

Environment for **Pytorch** execution using miniconda:
- pytorch: 2.0.0 (using compile function)
- cudnn: 8.8
- cuda: 11.7

Environment for **JAX** execution using docker:
- jax: 0.4.8
- jaxlib: 0.4.7+cuda11.cudnn82


**Result**
| Left-aligned | author's JAX implementation | Pytorch implementation (this repo) |
| :---         |     :---:      |          :---: |
| GPU usage | ~95% | ~60% |
| GPU memory usage   | ~11.8GB | ~5.4GB |
| FPS | 34.4 | 12.0 |

*FPS: the number of interaction with environments per second.

JAX implementation was surprisingly efficient.
I could run 2 experiments simultaneously on my local machine because GPU memory usage was small at pytorch implementation .
Therefore, in practice, the FPS was 34.4 for JAX and 17.5 (2experiments parallel) for Pytorch on my local machine.

I hope this information is helpful.

**Comment by younggyoseo** [comment]
Thank you! It's super helpful

**Comment by realjoenguyen** [comment]
@NM512 may i ask your results in the table is from dreamerv3 jax with `run.scripts` = "train" or "parallel" (using multiple workers + asynchronous results) ?

**Comment by NM512** [comment]
@realjoenguyen 
Hello,
For the comparison, I relied on the results available in the original repository, which you can find under the 'scores' section at [danijar/dreamerv3](https://github.com/danijar/dreamerv3/tree/main/scores). I believe using run.scripts set to "train_eval" is an approach for a fair evaluation score comparison.
