### ISSUE TITLE
TwoHotDistSymlog.mean and TwoHotDistSymlog.mode

### ISSUE THREAD

**Issue by zhangpaipai** [NM512/dreamerv3-torch#7]
Hi, what is the different between TwoHotDistSymlog.mean and TwoHotDistSymlog.mode. And why do we call the function mode 'mode'?
Thanks!
![图片](https://user-images.githubusercontent.com/54445533/234008228-bdac9c70-50b2-4366-bd13-baf65c767e44.png)

**Comment by NM512** [comment]
Thanks for asking.
The 'mode' means the value that appears most frequently in some probability distribution or set of data.
In case of gaussian distribution, 'mode' and 'mean' are exactly the same, but in case of gamma distribution they are different because of distribution shape.

In the paper TwoHotDistSymlog is defined as a way to do **continuous** value regression using **discrete** distribution(buckets).
And there is not any description to define distribution shape for TwoHotDistSymlog.
So I implemented mean and mode as a same function which outputs one continuous valus.

**Comment by NM512** [comment]
Thanks for asking.

The 'mode' means the value that appears most frequently in some probability distribution or set of data. For example, in case of gaussian distribution 'mode' and 'mean' are exactly the same, but in case of gamma distribution they are different because of distribution shape.

In the paper twohot symlog prediction is defined as a way to do continuous value regression using discrete distribution(buckets). And there is not any definition as a distribution of twohot symlog prediction. So I implemented mean and mode as a same function which outputs single continuous value according to the paper.

FYI I fixed confusing variable name in [this commit](https://github.com/NM512/dreamerv3-torch/commit/e5e8bcb2843bebe60798cbb10abbcfee4b6e35e0).
